# Generated by Django 3.2.5 on 2022-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_competitive_exams_mentor_data_mentor_list_placement_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_data',
            name='final_attendence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentor_data',
            name='final_cie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentor_data',
            name='la1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentor_data',
            name='la2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
