# Generated by Django 3.2.5 on 2022-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_auto_20220510_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_data',
            name='final_attendence',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='final_cie',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='la1',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='la2',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse1_attndence',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse1_marks',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse2_attndence',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse2_marks',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse3_attndence',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_data',
            name='mse3_marks',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
